- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - openstack-python3-jobs-arm64
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        # NOTE(TheJulia): re-enable voting once
        # https://review.opendev.org/c/openstack/ironic/+/910528
        # has merged.
        - ironic-tox-unit-with-driver-libs:
            voting: false
        - ironic-cross-sushy:
            voting: false
        - ironic-tempest-functional-python3
        # NOTE(JayF): This job is failing and is being fixed in master. It
        # should be re-enabled in stable when it's re-enabled on master.
        # commented out 2023-05-19
        - ironic-tempest-functional-rbac-scope-enforced:
            voting: false
        # NOTE(TheJulia): Marking non-voting until we can get
        # other banches sorted breakage wise.
        - ironic-grenade:
            voting: false
        - ironic-standalone:
            voting: false
        - ironic-standalone-redfish:
            voting: false
        - ironic-tempest-bios-redfish-pxe
        - ironic-tempest-uefi-redfish-vmedia
        # NOTE(TheJulia): Disabling until we can sort out the various
        # breaks with CI on this branch.
        # NOTE(TheJulia) Marking multinode non-voting on 20210311
        # Due to a high failure rate on limestone where the compute1
        # machine never appears to be able to communicate across the
        # vxlan tunnel, possible mtu issue, but non-voting until we
        # understand it in mind for the upcoming release.
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            voting: false
        - ironic-tempest-bios-ipmi-direct-tinyipa
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        # Non-voting jobs
        - ironic-tox-bandit:
            voting: false
        - ironic-inspector-tempest:
            voting: false
        - ironic-inspector-tempest-uefi-redfish-vmedia:
            voting: false
        - ironic-tempest-ipa-wholedisk-bios-ipmi-direct-dib:
            voting: false
        - ironic-standalone-anaconda:
            voting: false
        - ironic-inspector-tempest-rbac-scope-enforced:
            voting: false
        - bifrost-integration-tinyipa-ubuntu-focal:
            voting: false
        - bifrost-integration-redfish-vmedia-uefi-centos-9:
            voting: false
    gate:
      jobs:
        # NOTE(TheJulia): Return this to voting once
        # https://review.opendev.org/c/openstack/ironic/+/910528
        # or similar change to the branch has merged
        #- ironic-tox-unit-with-driver-libs
        - ironic-tempest-functional-python3
        # NOTE(JayF): This job is failing and is being fixed in master. It
        # should be re-enabled in stable when it's re-enabled on master.
        # commented out 2023-05-19
        #- ironic-tempest-functional-rbac-scope-enforced
        # NOTE(TheJulia): Disabling grenade since the branch before is no
        # longer supported.
        # - ironic-grenade
        # NOTE(TheJulia): Commenting out standalone jobs until we figure
        # out what is causing them to fail on mulitple branches.
        # - ironic-standalone
        # - ironic-standalone-redfish
        - ironic-tempest-bios-redfish-pxe
        - ironic-tempest-uefi-redfish-vmedia
        # NOTE(TheJulia): Disabled multinode on 20210311 due to Limestone
        # seeming to be 
        # - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode
        - ironic-tempest-bios-ipmi-direct-tinyipa
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        # NOTE(TheJulia): Disabling until we can the competing
        # gate fixes merged
    experimental:
      jobs:
        # TODO(dtantsur): these jobs are useful but currently hopelessly
        # broken. Fix them and bring back to the gate.
        - ironic-grenade-multinode-multitenant:
            voting: false
        - ironic-inspector-tempest-discovery-fast-track:
            voting: false
