- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-master-branch-jobs
      - openstack-python3-xena-jobs
      - openstack-python3-xena-jobs-arm64
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-tempest-functional-python3
        # NOTE(JayF): This job is failing and is being fixed in master. It
        # should be re-enabled in stable when it's re-enabled on master.
        # commented out 2023-05-19
        - ironic-standalone:
            voting: false
        - ironic-standalone-redfish:
            voting: false
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-wholedisk-bios-snmp-pxe
        - ironic-tempest-ipa-partition-pxe_ipmitool
        - ironic-tempest-ipa-partition-uefi-pxe_ipmitool
        # NOTE(TheJulia) Marking multinode non-voting on 20210311
        # Due to a high failure rate on limestone where the compute1
        # machine never appears to be able to communicate across the
        # vxlan tunnel, possible mtu issue, but non-voting until we
        # understand it in mind for the upcoming release.
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            voting: false
        - ironic-tempest-bios-ipmi-direct-tinyipa
        # NOTE(JayF): This job is failing and is being fixed in master. It
        # should be re-enabled in stable when it's re-enabled on master.
        # commented out 2023-05-19
        - ironic-tempest-bfv:
            voting: false
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        # Non-voting jobs
        - ironic-tox-bandit:
            voting: false
        - ironic-inspector-tempest:
            voting: false
        - ironic-inspector-tempest-managed-non-standalone:
            voting: false
        - ironic-inspector-tempest-partition-bios-redfish-vmedia:
            voting: false
        - ironic-tempest-ipa-wholedisk-bios-ipmi-direct-dib:
            voting: false
    gate:
      jobs:
        # NOTE(TheJulia): Return this to voting once
        # https://review.opendev.org/c/openstack/ironic/+/910528
        # or similar change to the branch has merged
        #- ironic-tox-unit-with-driver-libs
        - ironic-tempest-functional-python3
        # NOTE(JayF): This job is failing and is being fixed in master. It
        # should be re-enabled in stable when it's re-enabled on master.
        # commented out 2023-05-19
        # - ironic-standalone
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-wholedisk-bios-snmp-pxe
        - ironic-tempest-ipa-partition-pxe_ipmitool
        - ironic-tempest-ipa-partition-uefi-pxe_ipmitool
        # NOTE(TheJulia): Disabled multinode on 20210311 due to Limestone
        # seeming to be 
        # - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode
        - ironic-tempest-bios-ipmi-direct-tinyipa
        # NOTE(JayF): This job is failing and is being fixed in master. It
        # should be re-enabled in stable when it's re-enabled on master.
        # commented out 2023-05-19
        #- ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
    experimental:
      jobs:
        # TODO(dtantsur): these jobs are useful but currently hopelessly
        # broken. Fix them and bring back to the gate.
        - ironic-tempest-ipxe-ipv6:
            voting: false
        - ironic-inspector-tempest-discovery-fast-track:
            voting: false
